#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash or
#       ksh, then change the shebang line even further as explained above.
#
#   (2) Put the JAVA_HOME variable in your environment. It is used by this
#       script to locate java. By default the value of the JAVA_HOME
#       environment variable is used.
#
#   (3) For Cygwin or MSYS, switch paths to Windows format before running java
#       with the -classpath argument and update the JAVA_HOME variable so that
#       it refers to the Windows home of Java.
#
#   (4) We provide a "spring-wrapper.sh" script that does the actual work.
#       In order for this script to work, it must be in the same directory
#       as the Gradle distribution.
#

PROG="$0"
# Need this for relative symlinks.
while [ -h "$PROG" ] ; do
    ls=`ls -ld "$PROG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PROG="$link"
    else
        PROG=`dirname "$PROG"`"/$link"
    fi
done
SAVEPWD=`pwd`
cd "`dirname \"$PROG\"`" >/dev/null
PROG="`pwd`/`basename \"$PROG\"`"
cd "$SAVEPWD"

DIRNAME=`dirname "$PROG"`
# Java might not be in your PATH. Make sure to use the Java that Gradle was run with,
# stored in JAVA_HOME.
if [ -z "$JAVA_HOME" ] ; then
    JAVA="java"
else
    JAVA="$JAVA_HOME/bin/java"
fi

if [ ! -x "$JAVA" ] ; then
    echo "Error: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $JAVA" >&2
    exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "Warning: JAVA_HOME environment variable is not set."
fi

CLASSPATH=$( find "$DIRNAME" -name "gradle-wrapper.jar" )
MODULE_PATH=$( find "$DIRNAME" -type d -name "lib" )
if [ -z "$MODULE_PATH" ] ; then
    MODULE_PATH=""
else
    MODULE_PATH="--module-path $MODULE_PATH"
fi

if [ ! -f "$CLASSPATH" ] ; then
    echo "Error: Unable to locate gradle-wrapper.jar." >&2
    echo "Gradle may not be properly installed." >&2
    exit 1
fi

exec "$JAVA" $MODULE_PATH $JAVA_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
